config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.haml
- @books.each do |book|
  %ul
    %li
      = "#{book.title} by #{book.author}"

%p
  = link_to "Add book", new_book_path

app/views/books/new.html.haml
= form_for(@book) do |f|
  %p
    = f.text_field :title, :placeholder => "Add new book title"
  %p
    = f.text_field :author, :placeholder => "Add new author"
  %p
    = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>